### ISSUE TITLE
Cannot load testthat

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgload#159] opened 2021-05-04 09:03 UTC
This is probably happening because the dependencies of testthat and that of pkgload overlap. With most recent package versions, in particular cli 2.5.0, which does not import glue via the `NAMESPACE` any more:

```
❯ R -q --vanilla -e 'pkgload::load_all()'
> pkgload::load_all()
ℹ Loading testthat
>

❯ R -q --vanilla -e 'pkgload::load_all(quiet = TRUE)'
> pkgload::load_all(quiet = TRUE)
Error: Dependency package(s) 'waldo' not available.
Backtrace:
    █
 1. └─pkgload::load_all(quiet = TRUE)
 2.   └─pkgload:::load_imports(path)
 3.     └─pkgload:::abort_for_missing_packages(res, imports$package)
Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'waldo' not available.
Execution halted
```

**Comment by gaborcsardi** [comment] 2021-05-04 09:07
This is similar to #150, so maybe we'll just have to live with it (https://github.com/r-lib/pkgload/issues/150#issuecomment-790919204)?

**Comment by gaborcsardi** [comment] 2021-05-04 09:20
Maybe it is an issue between glue, actually, from here: https://github.com/tidyverse/glue/blob/f0a7b2a21162980c153edd68a9f5d279af1d426b/R/zzz.R#L3

Because the actual error, if we don't suppress it, looks like this:
```
❯ R -q --vanilla -e 'pkgload::load_all(quiet = TRUE)'
> pkgload::load_all(quiet = TRUE)
Loading required namespace: brio
Loading required namespace: digest
Loading required namespace: ellipsis
Loading required namespace: evaluate
Loading required namespace: jsonlite
Loading required namespace: lifecycle
Loading required namespace: praise
Loading required namespace: waldo
Failed with error:  ‘.onLoad failed in loadNamespace() for 'glue', details:
  call: get(genname, envir = envir)
  error: object 'compare' not found’
Loading required namespace: withr
Error: Dependency package(s) 'waldo' not available.
Backtrace:
    █
 1. └─pkgload::load_all(quiet = TRUE)
 2.   └─pkgload:::load_imports(path) /Users/gaborcsardi/works/pkgload/R/load.r:168:2
 3.     └─pkgload:::abort_for_missing_packages(res, imports$package) /Users/gaborcsardi/works/pkgload/R/imports-env.r:64:2
Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'waldo' not available.
Execution halted
```

**Comment by hadley** [comment] 2021-05-04 13:25
I bet it's this line: https://github.com/tidyverse/glue/blob/master/R/zzz.R#L3

Maybe just needs to use the same strategy as for vctrs?

**Comment by jimhester** [comment] 2021-05-04 13:28
I tried that, it makes no difference

**Comment by hadley** [comment] 2021-05-04 13:42
The problem is that glue needs testthat to be loaded in order to provide a method for the generic, and testthat needs glue to be loaded because cli needs? And the loading happens in such a way that "testthat" is included in `loadedNamespaces()` without actually being fully loaded?

**Comment by gaborcsardi** [comment] 2021-05-04 13:49
I think it is more difficult than that, because cli needing glue is not new. Actually when cli imported glue through `NAMESPACE`, this worked. But the new version of cli does not do that, and now it does not work.

If glue is loaded before `load_all()`-ing testthat, then there is no error, either. E.g. `quiet = FALSE` loads cli + glue, and then everything is fine.

**Comment by lionel-** [comment] 2022-05-30 07:56
I can't reproduce. This probably has been fixed by https://github.com/tidyverse/glue/commit/8ba80fe50fffd0db8c32066c8a60fe162611e0ed

**Closed by lionel-** 2022-05-30 07:56 UTC
