### ISSUE TITLE
`system.file()` problem in dependant packages

### ISSUE THREAD

**Issue by rkrug** [r-lib/pkgload#100] opened 2019-05-27 09:21 UTC
I have the following problem: 

I have one package `baseScheme` which contains the following function: 

```
make_example <- function(.packageName = "dmdScheme") {
  example_dir <- system.file("example_data", package = .packageName)
  examples <- list.dirs( example_dir, recursive = FALSE, full.names = FALSE)
 return(examples)
}
```

Now I have a package `newScheme` which depends on `baseScheme` and in which I want to be able to define the following function:

```
make_example <- baseScheme::make_example(.packageName)
```

This works when I 

1. load both packages via `load_all()` or
2. install both packages and load them via `library()`

But it does not work (i.e. it returns an empty string even if I have examples), if I load the `baseScheme` via `library()` and `newScheme` via `load_all()`.

I understand why this is the case (`load_all()` injects the code for `system.file()` to work with local packages only in the `newScheme` package, but not in the `baseScheme` package), but this makes life difficult when trying e.g. to use CMD-SHIFT-T to run the tests. 

Is there a way, of making this work?

**Comment by jimhester** [comment] 2019-05-28 12:55
This is a duplicate of https://github.com/r-lib/pkgload/issues/69, which has some workarounds.

One way to work around this is to use `fs::path_package()` rather than `system.file()` in the packages.

**Closed** 2019-05-28 12:55 UTC
