### ISSUE TITLE
Supply macro definitions in print.dev_help

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgload#120] opened 2020-01-01 23:58 UTC
`print.dev_topic()` — the documentation suggests that `...` in `Rd2txt()` and `Rd2html()` is passed on to `parse_Rd()`.  I don't remember exactly what you need to supply in the `macros` argument, but I'm pretty sure I got it working in pkgdown.

Would also need to work with the IDE team to get the necessary information passed along to the `previewRd()` API call.

**Comment by dmurdoch** [comment] 2020-05-14 09:30
This has come up in this discussion:  https://stat.ethz.ch/pipermail/r-package-devel/2020q2/005420.html.  The `mathjaxr` package supplies macros to allow MathJax to be used in Rd help files; packages need to list it in the `RdMacros` field in `DESCRIPTION`.  `pkgload::load_rd_macros()` should be looking there.

**Comment by lionel-** [comment] 2022-06-01 09:33
IIUC, this is a duplicate of #115 which was fixed in #116. Am I missing something @hadley?

**Comment by hadley** [comment] 2022-06-01 12:50
@lionel- I think @dmurdoch is saying that the current support is incomplete — as well as loading the macros defined in the current package, we also need to load the packages provided by the packages listed in the `RdMacros` field.

**Comment by lionel-** [comment] 2022-06-02 09:57
ok I think I understand now, we already have support for foreign and local RdMacros outside RStudio that Gabor implemented in #116. I have added unit tests in #205 (see also https://github.com/r-lib/pkgload/commit/e3c282a53a8addda3c08d19983c277c62dcbf0e2 which fixes a bug in RStudio introduced in this PR).

What was missing is support inside RStudio because we call into the IDE API in that case. @dmurdoch opened an issue about foreign macros in https://github.com/rstudio/rstudio/issues/6871 which has been fixed by Kevin since. However, it seems that local macros are still not loaded. I have opened https://github.com/rstudio/rstudio/issues/11336 to get this fixed.

I think we can now close this but please let me know if I'm still missing something.

**Comment by lionel-** [comment] 2022-06-03 08:00
Kevin found a way for us to display our own generated html files in the help pane of RStudio.

**Closed** 2022-06-06 10:24 UTC
Labels: feature
