### ISSUE TITLE
inst/* files in package loaded by load_all can't be found by other packages calling system.file

### ISSUE THREAD

**Issue by agoldst** [r-lib/pkgload#98] opened 2019-05-02 14:59 UTC
Though `load_all` supplies a "shim" for `system.file` for the package it loads, this won't help if other packages try to find `inst/*` files using `system.file`. Here's an example.

Let's create a package with an rmarkdown template.

```r
library(devtools)
create_package("devtoolsissue")
use_package("rmarkdown")
use_rmarkdown_template("tmpl")
```

RStudio now opens a new session in the `devtoolsissue` project directory. Now let's try to test whether the template can be used.

```r
devtools::load_all()
load_all_testfile <- tempfile(fileext=".Rmd")
rmarkdown::draft(f, "tmpl", "devtoolsissue", edit=F) # error

#> Error in rmarkdown::draft(f, "tmpl", "devtoolsissue", edit = F) :
#>     The template 'tmpl' was not found in the devtoolsissue package
```

But actually, there's no problem here if the package is installed for real:

```r
devtools::install()
install_testfile <- tempfile(fileext=".Rmd")
rmarkdown::draft(install_testfile, "tmpl", "devtoolsissue", edit=F) # ok
readLines(install_testfile, n=2)

#> [1] "---"                       "title: \"Template Title\""
```

Actual context where this is a problem: I have a package which supplies an rmarkdown template and has some testthat tests to verify this template can be processed correctly. But `devtools::test()` or RStudio "Test Package" leads to test failures because they load the package via `load_all`.

I understand that `load_all` is never going to perfectly mirror installing and loading, but I wondered if there's anything to be done here to help ensure meaningful test results.

**Comment by jimhester** [comment] 2019-05-02 15:21
This is a duplicate of https://github.com/r-lib/pkgload/issues/69, which also provides some workarounds.

**Closed by jimhester** 2019-05-02 15:21 UTC

**Comment by agoldst** [comment] 2019-05-02 15:27
thank you! sorry I missed the related earlier issue.
